"""
Importing every model here ensures they're all registered on
`Base.metadata` before Alembic's `env.py` (or anything else) inspects
it -- a common gotcha with SQLAlchemy declarative mapping is a model
that's never imported anywhere silently missing from autogenerated
migrations.
"""

from app.models.audit_log import AuditLog
from app.models.chat_history import ChatHistory
from app.models.fraud_explanation import FraudExplanation
from app.models.model_version import ModelVersion
from app.models.prediction import Prediction
from app.models.transaction import Transaction
from app.models.user import User
from app.models.user_session import UserSession

__all__ = [
    "AuditLog",
    "ChatHistory",
    "FraudExplanation",
    "ModelVersion",
    "Prediction",
    "Transaction",
    "User",
    "UserSession",
]
