"""initial schema: users, transactions, predictions, explanations, chat, model versions, audit logs

Revision ID: 2bb6878dd99a
Revises: 
Create Date: 2026-07-10 19:33:04.944131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bb6878dd99a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('version_tag', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_tag')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('v1', sa.Float(), nullable=False),
    sa.Column('v2', sa.Float(), nullable=False),
    sa.Column('v3', sa.Float(), nullable=False),
    sa.Column('v4', sa.Float(), nullable=False),
    sa.Column('v5', sa.Float(), nullable=False),
    sa.Column('v6', sa.Float(), nullable=False),
    sa.Column('v7', sa.Float(), nullable=False),
    sa.Column('v8', sa.Float(), nullable=False),
    sa.Column('v9', sa.Float(), nullable=False),
    sa.Column('v10', sa.Float(), nullable=False),
    sa.Column('v11', sa.Float(), nullable=False),
    sa.Column('v12', sa.Float(), nullable=False),
    sa.Column('v13', sa.Float(), nullable=False),
    sa.Column('v14', sa.Float(), nullable=False),
    sa.Column('v15', sa.Float(), nullable=False),
    sa.Column('v16', sa.Float(), nullable=False),
    sa.Column('v17', sa.Float(), nullable=False),
    sa.Column('v18', sa.Float(), nullable=False),
    sa.Column('v19', sa.Float(), nullable=False),
    sa.Column('v20', sa.Float(), nullable=False),
    sa.Column('v21', sa.Float(), nullable=False),
    sa.Column('v22', sa.Float(), nullable=False),
    sa.Column('v23', sa.Float(), nullable=False),
    sa.Column('v24', sa.Float(), nullable=False),
    sa.Column('v25', sa.Float(), nullable=False),
    sa.Column('v26', sa.Float(), nullable=False),
    sa.Column('v27', sa.Float(), nullable=False),
    sa.Column('v28', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_batch_id'), 'transactions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_ref'), 'transactions', ['external_ref'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chat_role'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_transaction_id'), 'chat_history', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('predicted_class', sa.Enum('FRAUD', 'LEGITIMATE', name='predicted_class'), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_risk_level'), 'predictions', ['risk_level'], unique=False)
    op.create_index(op.f('ix_predictions_transaction_id'), 'predictions', ['transaction_id'], unique=False)
    op.create_table('fraud_explanations',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fraud_explanations')
    op.drop_index(op.f('ix_predictions_transaction_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_risk_level'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_transaction_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_transactions_external_ref'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_batch_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('model_versions')
    # ### end Alembic commands ###

    # NOTE: Alembic's autogenerate does not emit DROP TYPE for native Postgres
    # ENUMs when the owning tables are dropped -- this is a known upstream
    # limitation, not an oversight. Left unhandled, downgrade-then-upgrade
    # fails with "type already exists". Dropped explicitly here, in reverse
    # dependency order, after all tables that reference them are gone.
    sa.Enum(name='risk_level').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='predicted_class').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='chat_role').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
